openapi: 3.0.3
info:
  title: Task API
  description: API for managing tasks
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Main API server

paths:
  /tasks:
    get:
      summary: Get a list of tasks
      operationId: getTasks
      parameters:
        - name: filter
          in: query
          description: Filter tasks by status (e.g., completed or not completed)
          required: false
          schema:
            type: string
            enum: [completed, not_completed]
        - name: sort
          in: query
          description: Sort tasks by a field (e.g., title, createdDate)
          required: false
          schema:
            type: string
            enum: [title, createdDate]
        - name: order
          in: query
          description: Order of sorting (e.g., ascending or descending)
          required: false
          schema:
            type: string
            enum: [asc, desc]
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTask'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
  /tasks/{taskId}:
    patch:
      summary: Update a task
      operationId: updateTask
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '404':
          description: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        createdDate:
          type: string
          format: date-time
      required:
        - id
        - title
        - completed

    NewTask:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
      required:
        - title

    UpdateTask:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
